sudo: required
# to avoid issue:
# https://github.com/kubernetes/kubernetes/issues/90077#issuecomment-718778960
# it set ubuntu version to be 20.04.1 LTS that
# includes docker kubernetes 19
dist: focal

# required services
services:
  - docker
env:
  global:
    # get SHA code for current head (master) and set it as env var
    - SHA=$(git rev-parse HEAD)
    # gcloud cli silent mode - disable prompts that require user input
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
  # decrypt service-account.json on travis server for gcloud
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d

  # install google cloud sdk
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc

  # install kubernetes in the google cloud
  - gcloud components update kubectl
  - gcloud components list


  # tell google cloud who we are
  # service account is equivalent of IAM user in AWS
  - gcloud auth activate-service-account --key-file service-account.json

  # set current project, zone and container
  - gcloud config set project multi-k8s-299812
  - gcloud config set compute/zone europe-north1-a
  - gcloud container clusters get-credentials multi-cluster

  # emit password from env var and pipe it to docker login stdin
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # make a test build
  - docker build -t shchepinsky/react-test -f ./client/Dockerfile.dev ./client

  # create image using ruby base image with dev tools
  # mount current working directory as /app
  # run 'sh' as default command
  # was used to encrypt service.account.json
  # - docker run -it -v $(pwd):/app ruby:2.4 sh

script:
  - docker run -e CI=true shchepinsky/react-test npm run test -- --coverage

deploy:
  # travis has no Kubernetes provider built in, so we provide a custom script
  provider: script
  script: bash ./deploy.sh
  # deploy only on updates to master branch
  on:
    branch: master

